from datetime import date, datetime, timedelta
from pathlib import Path

import pytest

from director import db
from director.blocks import OFF_AIR_END, OFF_AIR_START
from director.scheduler import generate_day, generate_schedule
from director.timeutil import combine_msk


def build_rich_library(conn):
    """5 series x 20 episodes (~20 min each), 30 ads (20-40s), 10 bumpers (~10s) -
    comfortably more than a broadcast day needs, so rotation never exhausts."""
    for s in range(5):
        conn.execute("INSERT INTO series (name, root_path) VALUES (?, ?)", (f"Show {s}", f"/show{s}"))
        series_id = conn.execute("SELECT id FROM series WHERE name = ?", (f"Show {s}",)).fetchone()["id"]
        for ep in range(1, 21):
            duration = 1200 + (ep % 3) * 60  # 20-22 min, a bit of variety
            conn.execute(
                "INSERT INTO episodes (series_id, season, episode, title, file_path, duration_seconds, scanned_at) "
                "VALUES (?, 1, ?, ?, ?, ?, datetime('now'))",
                (series_id, ep, f"Episode {ep}", f"/show{s}/e{ep}.mkv", duration),
            )
    for a in range(30):
        duration = 20 + (a % 5) * 5  # 20-40s
        conn.execute(
            "INSERT INTO ads (file_path, duration_seconds, scanned_at) VALUES (?, ?, datetime('now'))",
            (f"/ads/ad{a}.mp4", duration),
        )
    for kind in ("ad_in", "ad_out", "interstitial"):
        for b in range(3):
            conn.execute(
                "INSERT INTO bumpers (file_path, kind, duration_seconds, scanned_at) VALUES (?, ?, ?, datetime('now'))",
                (f"/bumpers/{kind}_{b}.mp4", kind, 8),
            )
    conn.commit()


def build_sparse_library(conn):
    """Only one series and no ads/bumpers at all. Random mode (not the
    'sequential' default) so the daily premiere cap doesn't apply and the
    rotation cursor keeps cycling the same 2 episodes indefinitely (that's
    correct - a rerun channel with a tiny library just repeats what it has);
    with no filler content available this exercises the path where ad
    breaks and the final padding loop toward 05:00 have nothing to insert."""
    conn.execute("INSERT INTO series (name, root_path, rotation_mode) VALUES ('Only Show', '/only', 'random')")
    series_id = conn.execute("SELECT id FROM series WHERE name = 'Only Show'").fetchone()["id"]
    for ep in range(1, 3):
        conn.execute(
            "INSERT INTO episodes (series_id, season, episode, title, file_path, duration_seconds, scanned_at) "
            "VALUES (?, 1, ?, ?, ?, 1200, datetime('now'))",
            (series_id, ep, f"Episode {ep}", f"/only/e{ep}.mkv"),
        )
    conn.commit()


def assert_day_is_contiguous(conn, broadcast_date: date):
    day_start = combine_msk(broadcast_date, OFF_AIR_END)
    day_end = combine_msk(broadcast_date + timedelta(days=1), OFF_AIR_END)
    rows = conn.execute(
        "SELECT * FROM program_log WHERE start_time >= ? AND start_time < ? ORDER BY start_time",
        (day_start.isoformat(), day_end.isoformat()),
    ).fetchall()
    assert rows, "expected at least one row"

    assert rows[0]["start_time"] == day_start.isoformat()
    assert rows[-1]["end_time"] == day_end.isoformat()
    assert rows[-1]["item_type"] == "off_air"

    for prev, nxt in zip(rows, rows[1:]):
        assert prev["end_time"] == nxt["start_time"], "gap or overlap between consecutive items"

    off_air_boundary = combine_msk(broadcast_date + timedelta(days=1), OFF_AIR_START).isoformat()
    for row in rows:
        if row["item_type"] == "episode":
            assert row["end_time"] <= off_air_boundary, "an episode ran past the 05:00 MSK off-air boundary"

    return rows


def test_generate_day_produces_contiguous_24h_timeline(tmp_path):
    conn = db.connect(tmp_path / "lib.db")
    build_rich_library(conn)

    broadcast_date = date(2026, 7, 6)  # a Monday, so DEFAULT_BLOCKS apply
    generate_day(conn, broadcast_date)
    rows = assert_day_is_contiguous(conn, broadcast_date)

    item_types = {row["item_type"] for row in rows}
    assert "episode" in item_types
    assert "ad" in item_types  # a 19h day at 20-25 min cadence should trigger multiple ad breaks
    assert "bumper" in item_types


def test_generate_day_handles_library_with_no_ads_or_bumpers(tmp_path):
    conn = db.connect(tmp_path / "lib.db")
    build_sparse_library(conn)

    broadcast_date = date(2026, 7, 6)
    generate_day(conn, broadcast_date)
    rows = assert_day_is_contiguous(conn, broadcast_date)

    # No ad/bumper content exists, so ad breaks degrade gracefully - but the
    # anchor padding still works, because continuity cards are generated by the
    # director, not drawn from the library.
    item_types = {row["item_type"] for row in rows}
    assert item_types <= {"episode", "card", "off_air"}
    assert "ad" not in item_types and "bumper" not in item_types

    # The episodes keep cycling right up to (at most one episode short of) the
    # nominal 05:00 MSK cutoff - off-air isn't hours early just because the
    # library is small, only up to the length of the last unfinished gap.
    off_air_row = rows[-1]
    off_air_duration = (
        datetime.fromisoformat(off_air_row["end_time"]) - datetime.fromisoformat(off_air_row["start_time"])
    ).total_seconds()
    assert 5 * 3600 <= off_air_duration <= 5 * 3600 + 1200


def test_generate_schedule_is_idempotent_per_day(tmp_path):
    conn = db.connect(tmp_path / "lib.db")
    build_rich_library(conn)

    start = date(2026, 7, 6)
    first = generate_schedule(conn, start, 2)
    assert all(count > 0 for count in first.values())

    second = generate_schedule(conn, start, 2)
    assert all(count == 0 for count in second.values())  # already generated -> skipped, no duplicates

    total_rows = conn.execute("SELECT COUNT(*) AS c FROM program_log").fetchone()["c"]
    # re-running generate_schedule must not have added anything
    third = generate_schedule(conn, start, 2)
    assert all(count == 0 for count in third.values())
    assert conn.execute("SELECT COUNT(*) AS c FROM program_log").fetchone()["c"] == total_rows


def test_weekend_event_override_is_applied(tmp_path):
    conn = db.connect(tmp_path / "lib.db")
    build_rich_library(conn)

    saturday = date(2026, 7, 4)
    assert saturday.weekday() == 5
    generate_day(conn, saturday)

    rows = conn.execute(
        "SELECT DISTINCT block_name, event_name FROM program_log WHERE event_name IS NOT NULL"
    ).fetchall()
    assert rows, "weekend generation should have used the marathon overlay"
    # Saturday composes marathon (daytime) + Adult Swim (night), so the event
    # label is the joined overlay names.
    assert all("выходной марафон" in r["event_name"] for r in rows)
    assert any(r["block_name"] == "марафон" for r in rows)


def _make_show0_adult(conn):
    conn.execute("UPDATE series SET category = 'adult-animation', rotation_mode = 'random' WHERE name = 'Show 0'")
    conn.commit()
    return conn.execute("SELECT id FROM series WHERE name = 'Show 0'").fetchone()["id"]


def test_adult_animation_airs_only_in_the_adult_swim_block_on_friday(tmp_path):
    from director.timeutil import utc_to_msk

    conn = db.connect(tmp_path / "lib.db")
    build_rich_library(conn)
    adult_sid = _make_show0_adult(conn)

    friday = date(2026, 7, 3)
    assert friday.weekday() == 4
    generate_day(conn, friday)

    rows = conn.execute(
        "SELECT pl.start_time FROM program_log pl JOIN episodes e ON e.id = pl.item_id "
        "WHERE pl.item_type = 'episode' AND e.series_id = ?",
        (adult_sid,),
    ).fetchall()
    assert rows, "adult-animation should air in the Friday Adult Swim block"
    for r in rows:
        hour = utc_to_msk(datetime.fromisoformat(r["start_time"])).hour
        assert hour >= 23 or hour < 2, f"adult-animation aired outside Adult Swim at MSK hour {hour}"


def test_adult_animation_never_airs_on_a_weekday(tmp_path):
    conn = db.connect(tmp_path / "lib.db")
    build_rich_library(conn)
    adult_sid = _make_show0_adult(conn)

    monday = date(2026, 7, 6)
    assert monday.weekday() == 0
    generate_day(conn, monday)

    aired = conn.execute(
        "SELECT COUNT(*) AS c FROM program_log pl JOIN episodes e ON e.id = pl.item_id "
        "WHERE pl.item_type = 'episode' AND e.series_id = ?",
        (adult_sid,),
    ).fetchone()["c"]
    assert aired == 0  # no Adult Swim on Mon-Thu, and adult-animation is barred everywhere else


def build_film(conn, title="Кино", reels=(1500, 1500, 1500)):  # 3 x 25min
    conn.execute("INSERT INTO films (title, root_path) VALUES (?, ?)", (title, f"/{title}"))
    fid = conn.execute("SELECT id FROM films WHERE title = ?", (title,)).fetchone()["id"]
    for i, d in enumerate(reels, start=1):
        conn.execute(
            "INSERT INTO reels (film_id, reel_number, file_path, duration_seconds, scanned_at) "
            "VALUES (?, ?, ?, ?, datetime('now'))",
            (fid, i, f"/{title}/r{i}.mkv", d),
        )
    conn.commit()
    return fid


def test_weekend_film_slot_places_a_film_as_film_marker_plus_reels(tmp_path):
    from director.timeutil import utc_to_msk

    conn = db.connect(tmp_path / "lib.db")
    build_rich_library(conn)
    conn.execute("UPDATE series SET rotation_mode = 'random'")  # keep daytime full so blocks start on time
    conn.commit()
    build_film(conn)

    saturday = date(2026, 7, 4)
    generate_day(conn, saturday)

    counts = {
        r["item_type"]: r["c"]
        for r in conn.execute(
            "SELECT item_type, COUNT(*) AS c FROM program_log WHERE block_name = 'вечерний фильм' GROUP BY item_type"
        ).fetchall()
    }
    assert counts.get("film", 0) == 1  # one EPG-visible programme marker
    assert counts.get("reel", 0) == 2  # the other two reels of the 3-reel film

    film_start = conn.execute("SELECT start_time FROM program_log WHERE item_type = 'film'").fetchone()["start_time"]
    msk = utc_to_msk(datetime.fromisoformat(film_start))
    assert (msk.hour, msk.minute) == (21, 0)  # the film tentpole starts on its 21:00 anchor


def test_raises_when_catalog_is_empty(tmp_path):
    conn = db.connect(tmp_path / "lib.db")
    with pytest.raises(RuntimeError):
        generate_day(conn, date(2026, 7, 6))


def test_ad_breaks_use_ad_in_and_ad_out_bumpers_specifically(tmp_path):
    conn = db.connect(tmp_path / "lib.db")
    build_rich_library(conn)

    generate_day(conn, date(2026, 7, 6))

    bumper_kinds_used = {
        r["kind"]
        for r in conn.execute(
            "SELECT b.kind FROM program_log pl JOIN bumpers b ON b.id = pl.item_id WHERE pl.item_type = 'bumper'"
        ).fetchall()
    }
    assert "ad_in" in bumper_kinds_used
    assert "ad_out" in bumper_kinds_used
    assert "interstitial" in bumper_kinds_used


def test_ad_load_never_exceeds_seven_minutes_in_any_rolling_hour(tmp_path):
    conn = db.connect(tmp_path / "lib.db")
    build_rich_library(conn)

    generate_day(conn, date(2026, 7, 6))

    ads = conn.execute(
        "SELECT start_time, end_time FROM program_log WHERE item_type = 'ad' ORDER BY start_time"
    ).fetchall()
    assert ads, "expected at least one ad to have been scheduled"

    # Brute-force check: for every ad's start time, sum ad seconds in the
    # trailing hour and confirm it never exceeds the 7-minute cap.
    from director.ad_pods import AD_CAP_SECONDS_PER_HOUR, ad_seconds_in_trailing_hour

    for row in ads:
        now = datetime.fromisoformat(row["start_time"]) + timedelta(seconds=1)
        assert ad_seconds_in_trailing_hour(conn, now) <= AD_CAP_SECONDS_PER_HOUR + 1  # small float slack


def test_double_ad_in_happens_sometimes_but_not_always(tmp_path, monkeypatch):
    conn = db.connect(tmp_path / "lib.db")
    build_rich_library(conn)

    # Force every coin-flip to hit the "double" branch.
    monkeypatch.setattr("director.scheduler.random.random", lambda: 0.0)
    generate_day(conn, date(2026, 7, 6))

    def count_consecutive_ad_in_pairs(conn):
        rows = conn.execute(
            "SELECT pl.id, pl.item_type, b.kind FROM program_log pl "
            "LEFT JOIN bumpers b ON b.id = pl.item_id AND pl.item_type = 'bumper' "
            "ORDER BY pl.start_time"
        ).fetchall()
        pairs = 0
        for prev, nxt in zip(rows, rows[1:]):
            if prev["kind"] == "ad_in" and nxt["kind"] == "ad_in":
                pairs += 1
        return pairs

    assert count_consecutive_ad_in_pairs(conn) > 0

    # And with the coin-flip forced the other way, it must never double up.
    conn2 = db.connect(tmp_path / "lib2.db")
    build_rich_library(conn2)
    monkeypatch.setattr("director.scheduler.random.random", lambda: 0.99)
    generate_day(conn2, date(2026, 7, 6))
    assert count_consecutive_ad_in_pairs(conn2) == 0


def test_premiere_series_air_at_most_once_per_day(tmp_path):
    # build_rich_library's 5 series are all 'sequential' (the schema default) -
    # a perfect bed for checking the daily cap end to end.
    conn = db.connect(tmp_path / "lib.db")
    build_rich_library(conn)

    generate_day(conn, date(2026, 7, 6))

    counts = conn.execute(
        """
        SELECT s.name, COUNT(*) AS airings FROM program_log pl
        JOIN episodes e ON e.id = pl.item_id
        JOIN series s ON s.id = e.series_id
        WHERE pl.item_type = 'episode'
        GROUP BY s.id
        """
    ).fetchall()

    assert len(counts) == 5  # every series still gets its one daily slot
    assert all(row["airings"] == 1 for row in counts)


def test_random_series_are_not_subject_to_the_premiere_cap(tmp_path):
    conn = db.connect(tmp_path / "lib.db")
    build_rich_library(conn)
    conn.execute("UPDATE series SET rotation_mode = 'random'")
    conn.commit()

    generate_day(conn, date(2026, 7, 6))

    counts = conn.execute(
        "SELECT COUNT(*) AS c FROM program_log WHERE item_type = 'episode'"
    ).fetchone()
    assert counts["c"] > 5  # far more than one slot each once the cap doesn't apply


def test_programs_are_padded_to_anchors_with_cards_not_interstitial_spam(tmp_path):
    """Anchoring rounds each slot up to the next quarter-hour with generated
    continuity cards, so programs are separated by cards - the interstitial
    bumper stays a last-resort filler, not a per-program separator."""
    conn = db.connect(tmp_path / "lib.db")
    build_rich_library(conn)
    conn.execute("UPDATE series SET rotation_mode = 'random'")  # plenty of content, no premiere cap in the way
    conn.commit()

    generate_day(conn, date(2026, 7, 6))

    rows = conn.execute(
        "SELECT pl.item_type, b.kind FROM program_log pl "
        "LEFT JOIN bumpers b ON b.id = pl.item_id AND pl.item_type = 'bumper' "
        "ORDER BY pl.start_time"
    ).fetchall()

    cards_used = sum(1 for r in rows if r["item_type"] == "card")
    episodes = sum(1 for r in rows if r["item_type"] == "episode")
    interstitials = sum(1 for r in rows if r["kind"] == "interstitial")

    assert cards_used > 0  # cards are what fill the tail of each slot up to the anchor
    assert interstitials < episodes  # not dropped between every program


def build_short_episode_library(conn):
    """One series of ~6:30 episodes (like Смешарики) - short enough that
    several share a single quarter-hour slot - plus a little ad/bumper content
    so ad breaks have something to draw from."""
    conn.execute("INSERT INTO series (name, root_path, rotation_mode) VALUES ('Shorts', '/shorts', 'random')")
    sid = conn.execute("SELECT id FROM series WHERE name = 'Shorts'").fetchone()["id"]
    for ep in range(1, 21):
        conn.execute(
            "INSERT INTO episodes (series_id, season, episode, title, file_path, duration_seconds, scanned_at) "
            "VALUES (?, 1, ?, ?, ?, 390, datetime('now'))",
            (sid, ep, f"E{ep}", f"/shorts/e{ep}.mkv"),
        )
    for a in range(10):
        conn.execute(
            "INSERT INTO ads (file_path, duration_seconds, scanned_at) VALUES (?, 25, datetime('now'))",
            (f"/ads/a{a}.mp4",),
        )
    for kind in ("ad_in", "ad_out"):
        conn.execute(
            "INSERT INTO bumpers (file_path, kind, duration_seconds, scanned_at) VALUES (?, ?, 8, datetime('now'))",
            (f"/bumpers/{kind}.mp4", kind),
        )
    conn.commit()


def test_short_episodes_share_a_quarter_slot(tmp_path):
    conn = db.connect(tmp_path / "lib.db")
    build_short_episode_library(conn)
    generate_day(conn, date(2026, 7, 6))

    rows = conn.execute("SELECT item_type FROM program_log ORDER BY start_time").fetchall()
    ep_to_ep = sum(
        1 for a, b in zip(rows, rows[1:]) if a["item_type"] == "episode" and b["item_type"] == "episode"
    )
    assert ep_to_ep > 0  # several short episodes butt directly against each other inside one slot


def test_each_program_run_starts_on_a_quarter_anchor(tmp_path):
    """Only the first program of each back-to-back run is anchor-aligned;
    packed short episodes after it run at ragged mid-slot times."""
    from director.timeutil import utc_to_msk

    conn = db.connect(tmp_path / "lib.db")
    build_short_episode_library(conn)
    generate_day(conn, date(2026, 7, 6))

    rows = conn.execute("SELECT start_time, item_type FROM program_log ORDER BY start_time").fetchall()
    for prev, cur in zip([None, *rows], rows):
        if cur["item_type"] != "episode":
            continue
        if prev is not None and prev["item_type"] == "episode":
            continue  # a mid-run packed short, not the anchored head of the run
        msk = utc_to_msk(datetime.fromisoformat(cur["start_time"]))
        assert msk.minute % 15 == 0 and msk.second == 0, f"program run starts off-anchor at {msk}"
