"""SQLite schema and connection helper for the media catalog."""

import sqlite3
from pathlib import Path

SCHEMA = """
CREATE TABLE IF NOT EXISTS series (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    root_path TEXT NOT NULL,
    rotation_mode TEXT NOT NULL DEFAULT 'sequential' CHECK (rotation_mode IN ('sequential', 'random')),
    category TEXT NOT NULL DEFAULT 'cartoon',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS episodes (
    id INTEGER PRIMARY KEY,
    series_id INTEGER NOT NULL REFERENCES series(id) ON DELETE CASCADE,
    season INTEGER NOT NULL DEFAULT 1,
    episode INTEGER,
    title TEXT,
    file_path TEXT NOT NULL UNIQUE,
    duration_seconds REAL,
    width INTEGER,
    height INTEGER,
    file_mtime REAL,
    file_size INTEGER,
    scanned_at TEXT NOT NULL,
    missing INTEGER NOT NULL DEFAULT 0,
    rendered_path TEXT,
    rendered_source_mtime REAL,
    rendered_source_size INTEGER
);
CREATE INDEX IF NOT EXISTS idx_episodes_series ON episodes(series_id, season, episode);

CREATE TABLE IF NOT EXISTS ads (
    id INTEGER PRIMARY KEY,
    file_path TEXT NOT NULL UNIQUE,
    category TEXT,
    duration_seconds REAL,
    width INTEGER,
    height INTEGER,
    file_mtime REAL,
    file_size INTEGER,
    scanned_at TEXT NOT NULL,
    missing INTEGER NOT NULL DEFAULT 0,
    rendered_path TEXT,
    rendered_source_mtime REAL,
    rendered_source_size INTEGER
);

CREATE TABLE IF NOT EXISTS bumpers (
    id INTEGER PRIMARY KEY,
    file_path TEXT NOT NULL UNIQUE,
    kind TEXT,
    duration_seconds REAL,
    width INTEGER,
    height INTEGER,
    file_mtime REAL,
    file_size INTEGER,
    scanned_at TEXT NOT NULL,
    missing INTEGER NOT NULL DEFAULT 0,
    rendered_path TEXT,
    rendered_source_mtime REAL,
    rendered_source_size INTEGER
);

-- Films are long-form tentpoles the user pre-splits into reels at natural
-- ad-break points. A film mirrors a series; its reels mirror episodes (same
-- rendered_* columns) so the ntsc-rs pre-render and playout resolve them with
-- the existing machinery. The scheduler lays a film as one 'film' program_log
-- row (the first reel, the EPG-visible programme marker) followed by 'reel'
-- rows, with ad breaks between.
CREATE TABLE IF NOT EXISTS films (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL UNIQUE,
    root_path TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'film',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS reels (
    id INTEGER PRIMARY KEY,
    film_id INTEGER NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    reel_number INTEGER NOT NULL,
    title TEXT,
    file_path TEXT NOT NULL UNIQUE,
    duration_seconds REAL,
    width INTEGER,
    height INTEGER,
    file_mtime REAL,
    file_size INTEGER,
    scanned_at TEXT NOT NULL,
    missing INTEGER NOT NULL DEFAULT 0,
    rendered_path TEXT,
    rendered_source_mtime REAL,
    rendered_source_size INTEGER
);
CREATE INDEX IF NOT EXISTS idx_reels_film ON reels(film_id, reel_number);

CREATE TABLE IF NOT EXISTS play_history (
    id INTEGER PRIMARY KEY,
    item_type TEXT NOT NULL CHECK (item_type IN ('episode', 'ad', 'bumper')),
    item_id INTEGER NOT NULL,
    played_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_play_history_item ON play_history(item_type, item_id, played_at);

CREATE TABLE IF NOT EXISTS program_log (
    id INTEGER PRIMARY KEY,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    item_type TEXT NOT NULL CHECK (item_type IN ('episode', 'ad', 'bumper', 'card', 'film', 'reel', 'sms_chat', 'off_air')),
    item_id INTEGER,
    block_name TEXT,
    event_name TEXT,
    status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'played', 'skipped')),
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_program_log_start ON program_log(start_time);
CREATE INDEX IF NOT EXISTS idx_program_log_item ON program_log(item_type, item_id, start_time);

CREATE TABLE IF NOT EXISTS ticker_pools (
    id INTEGER PRIMARY KEY,
    generated_at TEXT NOT NULL,
    msk_date TEXT NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('gemini', 'fallback')),
    lines_json TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ticker_pools_msk_date ON ticker_pools(msk_date);

-- Continuity cards (EPG/weather/clock). Unlike episodes/ads/bumpers these are
-- GENERATED by the director, not scanned from disk: the scheduler reserves a
-- slot with a kind + exact target_seconds (the "rubber" that pads a block up to
-- a quarter-hour anchor), and the profilaktika render job later fills
-- rendered_path. Played through program_player exactly like a pre-rendered file.
CREATE TABLE IF NOT EXISTS cards (
    id INTEGER PRIMARY KEY,
    kind TEXT NOT NULL,                 -- 'epg_day' | 'epg_next' | 'weather' | 'clock'
    msk_date TEXT NOT NULL,             -- broadcast day this card belongs to
    slot_start TEXT NOT NULL,           -- scheduled air time (UTC ISO); epg_next reads programs after this
    target_seconds REAL NOT NULL,       -- exact duration to render to (set by the scheduler for anchoring)
    spec_json TEXT,                     -- optional extra render params
    rendered_path TEXT,
    duration_seconds REAL,              -- actual rendered length (should equal target_seconds)
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'rendered', 'failed')),
    generated_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_cards_status ON cards(status, slot_start);
CREATE INDEX IF NOT EXISTS idx_cards_msk_date ON cards(msk_date);

CREATE TABLE IF NOT EXISTS weather_pools (
    id INTEGER PRIMARY KEY,
    generated_at TEXT NOT NULL,
    msk_date TEXT NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('gemini', 'fallback')),
    forecast_json TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_weather_pools_msk_date ON weather_pools(msk_date);

-- Generic per-MSK-day text pool for the service layer (currency rates,
-- horoscope, night SMS-chat) - same idempotent pattern as weather/ticker,
-- generalized by `kind` so new service content doesn't need a new table.
CREATE TABLE IF NOT EXISTS service_pools (
    id INTEGER PRIMARY KEY,
    kind TEXT NOT NULL,             -- 'currency' | 'horoscope' | 'sms'
    generated_at TEXT NOT NULL,
    msk_date TEXT NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('gemini', 'fallback')),
    payload_json TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_service_pools_kind_date ON service_pools(kind, msk_date);
"""


def _widen_program_log_item_type(conn: sqlite3.Connection) -> None:
    """SQLite can't ALTER a CHECK constraint, so adding 'card' (and future
    'film'/'reel') to program_log.item_type needs a full table rebuild. Guarded
    by the current constraint text so it runs exactly once, and done as one
    transaction (program_log is the live channel's state - see PROJECT_PLAN
    §6.3 for why we're careful with it). No other table references program_log
    by foreign key, so the RENAME is safe with foreign_keys ON.
    """
    row = conn.execute(
        "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'program_log'"
    ).fetchone()
    if row is None or "'sms_chat'" in row["sql"]:
        return  # fresh DB (created from SCHEMA with the current constraint) or already migrated

    conn.executescript(
        """
        BEGIN;
        ALTER TABLE program_log RENAME TO program_log_old;
        CREATE TABLE program_log (
            id INTEGER PRIMARY KEY,
            start_time TEXT NOT NULL,
            end_time TEXT NOT NULL,
            item_type TEXT NOT NULL CHECK (item_type IN ('episode', 'ad', 'bumper', 'card', 'film', 'reel', 'sms_chat', 'off_air')),
            item_id INTEGER,
            block_name TEXT,
            event_name TEXT,
            status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'played', 'skipped')),
            created_at TEXT NOT NULL DEFAULT (datetime('now'))
        );
        INSERT INTO program_log (id, start_time, end_time, item_type, item_id, block_name, event_name, status, created_at)
            SELECT id, start_time, end_time, item_type, item_id, block_name, event_name, status, created_at
            FROM program_log_old;
        DROP TABLE program_log_old;
        CREATE INDEX IF NOT EXISTS idx_program_log_start ON program_log(start_time);
        CREATE INDEX IF NOT EXISTS idx_program_log_item ON program_log(item_type, item_id, start_time);
        COMMIT;
        """
    )


def _migrate(conn: sqlite3.Connection) -> None:
    """CREATE TABLE IF NOT EXISTS doesn't add columns to a table that already
    exists from before this column was introduced - patch those in here."""
    series_cols = {row["name"] for row in conn.execute("PRAGMA table_info(series)")}
    if "rotation_mode" not in series_cols:
        conn.execute("ALTER TABLE series ADD COLUMN rotation_mode TEXT NOT NULL DEFAULT 'sequential'")
    if "category" not in series_cols:
        conn.execute("ALTER TABLE series ADD COLUMN category TEXT NOT NULL DEFAULT 'cartoon'")

    for table in ("episodes", "ads", "bumpers"):
        cols = {row["name"] for row in conn.execute(f"PRAGMA table_info({table})")}
        if "rendered_path" not in cols:
            conn.execute(f"ALTER TABLE {table} ADD COLUMN rendered_path TEXT")
        if "rendered_source_mtime" not in cols:
            conn.execute(f"ALTER TABLE {table} ADD COLUMN rendered_source_mtime REAL")
        if "rendered_source_size" not in cols:
            conn.execute(f"ALTER TABLE {table} ADD COLUMN rendered_source_size INTEGER")

    conn.commit()
    _widen_program_log_item_type(conn)


def connect(db_path: Path) -> sqlite3.Connection:
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    conn.executescript(SCHEMA)
    _migrate(conn)
    return conn
